apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: glit
  name: gobland-it-nginx
  labels:
    tier: glit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: glit
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        tier: glit
    spec:
      restartPolicy: Always

      containers:
      - name: gobland-it-nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /code
          name: code
        - name: config
          mountPath: /etc/nginx/conf.d

      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: gobland-it-code-php
      - name: config
        configMap:
          name: gobland-it-nginx
          items:
          - key: config
            path: site.conf
