apiVersion: v1
kind: Service

metadata:
  namespace: glit
  name: gobland-it-nginx-svc
  labels:
    tier: glit
spec:
  selector:
    app: nginx
    tier: glit
  ports:
  - protocol: TCP
    port: 80
