#!/usr/bin/perl
use warnings;
use strict;

use lib '/home/gobland-bot/lib/';
use GLB::HTML;

GLB::HTML::createIndex();
GLB::HTML::createEquipement();
GLB::HTML::createComposants();
GLB::HTML::createProfil();
GLB::HTML::createVue();
