#!/usr/bin/perl
use warnings;
use strict;

use lib '/home/gobland-bot/lib/';
use GLB::HTML::createIndex;
use GLB::HTML::createEquipement;
use GLB::HTML::createMateriaux;
use GLB::HTML::createComposants;
use GLB::HTML::createProfil;
use GLB::HTML::createVue;
use GLB::HTML::createPXBank;
use GLB::HTML::createGPS;
use GLB::HTML::createCavernes;
use GLB::HTML::createCdM;
use GLB::HTML::createSuivantVue;
use GLB::HTML::createRadar;
use GLB::queries;
use GLB::GLAPI;
use GLB::variables;

my $glyaml  = $GLB::variables::glyaml;

GLB::GLAPI::GetClanMembres($glyaml);
GLB::GLAPI::GetClanMembres2($glyaml);
GLB::GLAPI::getClanSkills($glyaml);
GLB::GLAPI::GetClanEquipement($glyaml);
GLB::GLAPI::getClanCavernes($glyaml);
GLB::GLAPI::getClanCafards($glyaml);
GLB::GLAPI::getMeuteMembres($glyaml);
GLB::GLAPI::getMPBot($glyaml);
GLB::GLAPI::getVue($glyaml);

GLB::functions::GetCompsTT();

GLB::HTML::createIndex::main();
GLB::HTML::createEquipement::main();
GLB::HTML::createMateriaux::main();
GLB::HTML::createComposants::main();
GLB::HTML::createProfil::main();
GLB::HTML::createVue::main();
GLB::HTML::createPXBank::main();
GLB::HTML::createGPS::main();
GLB::HTML::createCavernes::main();
GLB::HTML::createCdM::main();
GLB::HTML::createSuivantVue::main();
GLB::HTML::createRadar::main();
