#!/usr/bin/python3 -u
import re
import discord
import sys
import os
import asyncio
import inspect

from queries import *
from datetime import datetime,timedelta

token    = os.environ['TOKEN']
client   = discord.Client()
channels = eval(os.environ['CHANNELS'])

@client.event
async def on_ready():
    now_str  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    for channel_name in channels:
        channel = discord.utils.get(client.get_all_channels(), name=channel_name)

        if channel:
            answer = ':partying_face: Salutations, votre serviteur est là !'
            print('{} {:<20} {} | {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel, answer))
            #await channel.send(answer)

@client.event
async def on_message(message):
    now_str  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # we do not want the bot to reply outside registered clan channels
    channel = str(message.channel)
    if channel not in channels:
        return
    else:
        db_name   = channels[channel]

    # we do not want the bot to reply to itself
    if message.author == client.user:
        return

    if message.content.startswith('!!help'):
        print('{} {:<20} {} | [{}] !!help'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel,message.author))
        h_oukilest = '!!oulikest ID  -> Renvoie la position de <ID>\n'
        h_cdm      = '!!cdm ID       -> Renvoie la dernière CdM de <ID>\n'
        help       = '```' + h_oukilest + h_cdm + '```'
        await message.channel.send(help)

    elif message.content.startswith('!!oukilest'):
        m = re.match(r"!!oukilest (?P<id>\d*)", message.content)
        if m is not None:
            print('{} {:<20} {} | [{}] !!oukilest {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel,
                                                             message.author,m.group('id')))
            stats = oukilest(m.group('id'),db_name)
            if stats:
                # Id,Nom,Niveau,Type,Clan,X,Y,N,Z
                id   = stats[0]
                name = stats[1]
                niv  = stats[2]
                x    = stats[5]
                y    = stats[6]
                n    = stats[7]
                msgLine  = '[{}] {} ({}) : [ {:>4} | {:>4} | {:>4} ]'.format(id,name,niv,x,y,n)
                answer   = '```' + msgLine + '```'
            else:
                answer   = 'Informations non trouvées en DB(' + db_name + ') pour ID: ' + m.group('id')
            await message.channel.send(answer)
        else:
            answer   = '<ID> n\'est pas un nombre entier [REGEX: (\d*)]'
        print('{} {:<20} {} | [{}] !!oukilest {} | {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel,
                                                         message.author, m.group('id'),
                                                         answer))

    elif message.content.startswith('!!cdm'):
        m = re.match(r"!!cdm (?P<id>\d*)", message.content)
        if m is not None:
            print('{} {:<20} {} | [{}] !!cdm {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel,
                                                             message.author,m.group('id')))
            stats = cdm(m.group('id'),db_name)
            if stats:

                # Looking for position if the mob is in Vue
                pos = oukilest(m.group('id'),db_name)
                if pos:
                    x      = stats[5]
                    y      = stats[6]
                    n      = stats[7]
                    msgpos = '[ {:>4} | {:>4} | {:>4} ]'.format(x,y,n)

                # Id,Date,IdMob,Name,Niveau,Type,PVMin,PVMax,Blessure,
                # ATTMin,ATTMax,ESQMin,ESQMax,DEGMin,DEGMax
                # REGMin,REGMax,ARMMin,ARMmax,PERMin,PERMax

                date = stats[1]
                id   = stats[2]
                name = stats[3]
                niv  = stats[5]

                pvs = '{}-{}'.format(stats[6],stats[7])
                att = '{}-{}'.format(stats[9],stats[10])
                esq = '{}-{}'.format(stats[11],stats[12])
                deg = '{}-{}'.format(stats[13],stats[14])
                reg = '{}-{}'.format(stats[15],stats[16])
                arm = '{}-{}'.format(stats[17],stats[18])
                per = '{}-{}'.format(stats[19],stats[20])

                if pos:
                    msgLine  = '[{}] {} ({}) : {}\n'.format(id,name,niv,msgpos)
                else:
                    msgLine  = '[{}] {} ({})\n'.format(id,name,niv)

                msgdate  = 'CdM : {}\n'.format(date)
                msgpvs   = 'PVs : {} (~{}%)\n'.format(pvs,stats[8])
                msgatt   = 'ATT : {}\n'.format(att)
                msgdeg   = 'DEG : {}\n'.format(deg)
                msgesq   = 'ESQ : {}\n'.format(esq)
                msgreg   = 'REG : {}\n'.format(reg)
                msgarm   = 'Arm : {}\n'.format(arm)
                msgper   = 'PER : {}\n'.format(per)

                answer   = '```' + msgLine + msgdate + msgpvs + msgatt + msgdeg + msgesq + msgreg + msgarm + msgper + '```'
            else:
                answer   = 'Informations non trouvées en DB(' + db_name + ') pour ID: ' + m.group('id')
            await message.channel.send(answer)
        else:
            answer   = '<ID> n\'est pas un nombre entier [REGEX: (\d*)]'
        print('{} {:<20} {} | [{}] !!cdm {} | {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel,
                                                         message.author, m.group('id'),
                                                         answer.splitlines()[0]))

# Tasks definitions

async def task_5min_kills():
    while client.is_ready:
        for channel_name, db_name in channels.items():
            then     = datetime.now() - timedelta(minutes=5)
            then_str = then.strftime("%Y-%m-%d %H:%M:%S")
            now_str  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            channel  = discord.utils.get(client.get_all_channels(), name=channel_name)

            if channel: print('{} {:<20} {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel))

            infos = kills(then_str,db_name)
            if infos and channel:
                for row in infos:
                    # IdGob,Gobelin,PMSubject,PMDate,PMText,Date
                    idgob  = row[0]
                    nomgob = row[1]
                    pms    = row[2]
                    icon   = ':crossed_swords:'

                    m = re.search(r" - (?P<mob>.*)", pms)
                    if m is not None:
                        answer = '{} [{}] {} a tué {}'.format(icon,idgob,nomgob,m.group('mob'))
                        print('{} {:<20} {} | {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel, answer))

                        await channel.send(answer)

        await asyncio.sleep(300) # task runs every 300 seconds / 5 minutes

async def task_5min_baratins():
    while client.is_ready:
        for channel_name, db_name in channels.items():
            then     = datetime.now() - timedelta(minutes=5)
            then_str = then.strftime("%Y-%m-%d %H:%M:%S")
            now_str  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            channel  = discord.utils.get(client.get_all_channels(), name=channel_name)

            if channel: print('{} {:<20} {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel))

            infos = baratins(then_str,db_name)
            if infos and channel:
                for row in infos:
                    # IdGob,Gobelin,PMSubject,PMDate,PMText
                    idgob  = row[0]
                    nomgob = row[1]
                    pms    = row[2]
                    icon   = ':cyclone:'

                    m = re.search(r" - (?P<mob>.*)", pms)
                    if m is not None:
                        answer = '{} [{}] {} a baratiné {}'.format(icon,idgob,nomgob,m.group('mob'))
                        print('{} {:<20} {} | {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel, answer))

                        await channel.send(answer)

        await asyncio.sleep(300) # task runs every 300 seconds / 5 minutes

async def task_5min_wounded():
    while client.is_ready:
        for channel_name, db_name in channels.items():
            then     = datetime.now() - timedelta(minutes=5)
            then_str = then.strftime("%Y-%m-%d %H:%M:%S")
            now_str  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            channel  = discord.utils.get(client.get_all_channels(), name=channel_name)

            if channel: print('{} {:<20} {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel))

            stats = wounded(then_str,db_name)
            if stats and channel:
                for row in stats:
                    # Id,IdGob,PMDate,PMSubject,PMText,Date
                    pms    = row[3]
                    pmt    = row[4]
                    add    = ''
                    icon   = ':dart:'

                    m = re.search(r"\[(?P<idmob>\d*)\] (?P<nommob>.*)", pms)
                    if m is not None:
                        o = re.search(r"Points de Vie : entre (?P<pvmin>\d*) et (?P<pvmax>\d*)", pmt)
                        n = re.search(r"Blessure : (?P<bless>\d*)", pmt)

                        if o is not None:
                            min = (100 - int(n.group('bless'))) * int(o.group('pvmin')) / 100
                            max = (100 - int(n.group('bless'))) * int(o.group('pvmax')) / 100

                            if round(min) <= 0:
                                add = ', < {} PV restants'.format(round(max))
                            else:
                                add = ', ~ {} à {} PV restants'.format(round(min),round(max))

                        if n is not None:
                            answer = '{} [{}] {} est à finir (Blessé à {}%{})'.format(icon,m.group('idmob'),m.group('nommob'),n.group('bless'),add)
                            print('{} {:<20} {} | {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel, answer))

                            await channel.send(answer)

        await asyncio.sleep(300) # task runs every 300 seconds / 5 minutes

async def task_5min_deaths():
    while client.is_ready:
        for channel_name, db_name in channels.items():
            then     = datetime.now() - timedelta(minutes=5)
            then_str = then.strftime("%Y-%m-%d %H:%M:%S")
            now_str  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            channel  = discord.utils.get(client.get_all_channels(), name=channel_name)

            if channel: print('{} {:<20} {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel))

            deaths = death(then_str,db_name)
            if deaths and channel:
                for row in deaths:
                    # IdGob,Gobelin,PMSubject,PMDate,PMText,Date
                    idgob  = row[0]
                    nomgob = row[1]
                    icon   = ':pirate_flag:'

                    answer = '{} [{}] {} est mort(e)'.format(icon,idgob,nomgob)
                    print('{} {:<20} {} | {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel, answer))

                    await channel.send(answer)

        await asyncio.sleep(300) # task runs every 300 seconds / 5 minutes

async def task_5min_drops():
    while client.is_ready:
        for channel_name, db_name in channels.items():
            then     = datetime.now() - timedelta(minutes=5)
            then_str = then.strftime("%Y-%m-%d %H:%M:%S")
            now_str  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            channel  = discord.utils.get(client.get_all_channels(), name=channel_name)

            if channel: print('{} {:<20} {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel))

            infos = drops(then_str,db_name)
            if infos and channel:
                for row in infos:
                    # PMText
                    pmt    = row[0]
                    icon   = ':truck:'

                    m = re.search(r"^<B>\[(?P<idcot>\d*)\] (?P<nomcot>.*)<\/B>.*>(?P<nommob>.*) \((?P<idmob>\d*)\)<", pmt)
                    if m is not None:
                        answer = '{} [{}] {} a déposé sa cargaison à {} ({})'.format(icon,m.group('idmob'),m.group('nommob'),m.group('nomcot'),m.group('idcot'))
                        print('{} {:<20} {} | {}'.format(now_str, '[' + inspect.stack()[0][3] + ']', channel, answer))

                        await channel.send(answer)

        await asyncio.sleep(300) # task runs every 300 seconds / 5 minutes

client.loop.create_task(task_5min_kills())
client.loop.create_task(task_5min_baratins())
client.loop.create_task(task_5min_wounded())
client.loop.create_task(task_5min_deaths())
client.loop.create_task(task_5min_drops())
client.run(token)
