FROM alpine:3.7
MAINTAINER @Lordslair

RUN apk update \
    && apk add --no-cache perl perl-libwww perl-dbi perl-dbd-sqlite \
    && apk add --no-cache --virtual .build-deps \
                                    curl make perl-dev libc-dev gcc bash tzdata \
    && curl -L https://cpanmin.us | perl - App::cpanminus --no-wget \
    && cpanm --no-wget YAML::Tiny \
                       File::Pid \
    && cp /usr/share/zoneinfo/Europe/Paris /etc/localtime \
    && apk del .build-deps \
    && rm -rf /root/.cpanm
