apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  namespace: glit
  name: gobland-it-code-php
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
