apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: glit
  name: gobland-it-phpmyadmin
  labels:
    tier: glit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
      tier: glit
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: glit
    spec:

      containers:
        - name: gobland-it-phpmyadmin
          image: phpmyadmin/phpmyadmin:5
          ports:
            - containerPort: 8080
          env:
            - name: PMA_HOST
              value: gobland-it-mariadb-svc
            - name: PMA_PORT
              valueFrom:
                secretKeyRef:
                  name: gobland-it-mariadb-secret
                  key: port
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gobland-it-mariadb-secret
                  key: pass
