apiVersion: v1
kind: Service

metadata:
  namespace: glit
  name: gobland-it-phpmyadmin-svc
  labels:
    tier: glit
spec:
  selector:
    app: phpmyadmin
    tier: glit
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
