apiVersion: v1
kind: Service
metadata:
  name: mon-prometheus
  namespace: monitoring
  labels:
    tier: infra
spec:
  selector:
    app: prometheus
    tier: infra
  ports:
  - protocol: TCP
    port: 9090
