apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobland-it-perl
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perl
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: perl
        tier: backend
    spec:
      restartPolicy: Always

      containers:
      - name: gobland-it-perl
        image: alpine:3.7
        command: ["/bin/sh"]
        args: [
         "-c",
         "(
              wget -O - https://raw.githubusercontent.com/lordslair/gobland-bot/master/kubernetes/perl/entrypoint.sh | sh
          ) || echo 1"
        ]
        env:
        - name: DBLIST
          value: "XX,YY"
        - name: MARIADB_ROOT_PASSWORD
          value: YYYYY
