apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobland-it-nginx
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      initContainers:
      - name: gobland-it-php-init
        image: busybox
        volumeMounts:
        - name: code
          mountPath: /code
        command: ["/bin/sh"]
        args: [
         "-c",
         "(
              wget   https://github.com/lordslair/gobland-bot/archive/master.zip -O /code/gobland-it.zip &&
              unzip  /code/gobland-it.zip -d /code/ &&
              cp -a  /code/gobland-bot-master/kubernetes/php/* /code/ &&
              rm -rf /code/gobland-bot-master /code/gobland-it.zip
          ) || echo 1"
        ]
      containers:
      - name: gobland-it-nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /code
          name: code
        - name: config
          mountPath: /etc/nginx/conf.d
      restartPolicy: Always
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: gobland-it-code-php
      - name: config
        configMap:
          name: gobland-it-nginx
          items:
          - key: config
            path: site.conf
