apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobland-it-python
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: python
        tier: backend
    spec:
      initContainers:
      - name: gobland-it-python-init
        image: busybox
        volumeMounts:
        - name: code
          mountPath: /code
        command: ["/bin/sh"]
        args: [
         "-c",
         "(
              wget   https://github.com/lordslair/gobland-bot/archive/master.zip -O /code/gobland-it.zip &&
              unzip  /code/gobland-it.zip -d /code/ &&
              cp -a  /code/gobland-bot-master/kubernetes/python/* /code/ &&
              rm -rf /code/gobland-bot-master /code/gobland-it.zip
          ) || echo 1"
        ]
      containers:
      - name: gobland-it-python
        image: alpine:3.7
        command: ["/code/entrypoint.sh"]
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: YYYYY
        - name: TOKEN
          value: AAAAA
        volumeMounts:
        - mountPath: /code
          name: code
      restartPolicy: Always
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: gobland-it-code-python
