apiVersion: v1
kind: Deployment
metadata:
  name: gobland-it-php
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      restartPolicy: Always
      containers:
      - name: gobland-it-php
        image: php:fpm-alpine
        command: ["/code/entrypoint.sh"]
        volumeMounts:
        - mountPath: /code
          name: code
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: YYYYY
        - name: CLANNAME
          value: "ZZZZZ"
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: gobland-it-code-php
