apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobland-it-phpmyadmin
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
      tier: backend
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: backend
    spec:
      containers:
        - name: gobland-it-phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 8080
          env:
            - name: PMA_HOST
              value: gobland-it-mariadb
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: YYYYY
