apiVersion: v1
kind: Deployment
metadata:
  name: gobland-it-nginx
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      restartPolicy: Always
      containers:
      - name: gobland-it-nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
        - mountPath: /code
          name: code
      volumes:
      - name: config
        configMap:
          name: gobland-it-nginx
          items:
          - key: config
            path: site.conf
      - name: code
        persistentVolumeClaim:
          claimName: gobland-it-code-php
