apiVersion: v1
kind: Secret

metadata:
  namespace: glit
  name: gobland-it-mariadb-secret
type: Opaque
stringData:
  user: root
  pass: <pass>
  port: <port>
  host: <host>
---
  apiVersion: v1
  kind: Secret

  metadata:
    namespace: glit
    name: gobland-it-perl-secret
  type: Opaque
  stringData:
    dblist: "XX,YY"
