apiVersion: v1
kind: Secret

metadata:
  namespace: glit
  name: gobland-it-mariadb-secret
type: Opaque
stringData:
  user: root
  pass: <pass>
  port: <port>
  host: <host>
---
  apiVersion: v1
  kind: Secret

  metadata:
    namespace: glit
    name: gobland-it-perl-secret
  type: Opaque
  stringData:
    dblist: "XX,YY"
    frequency: '3600' # in seconds
---
apiVersion: v1
kind: Secret

metadata:
  namespace: glit
  name: gobland-it-backup-secret
type: Opaque
stringData:
  dblist: "XX,YY"
  pcauser: pca
  pcapass: <pass>
---
apiVersion: v1
kind: Secret

metadata:
  namespace: glit
  name: gobland-it-python-secret
type: Opaque
stringData:
  token: <token>
  channels: "{'channel-name': 'XX','channel-name': 'YY'}"
