apiVersion: v1
kind: Service

metadata:
  namespace: glit
  name: gobland-it-lb
  labels:
    tier: glit
spec:
  type: LoadBalancer
  selector:
    app: nginx
    tier: glit
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
