apiVersion: v1
kind: Service
metadata:
  name: gobland-it-phpmyadmin
  labels:
    tier: backend
spec:
  selector:
    app: phpmyadmin
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
