apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gobland-it-mariadb-db
spec:
  storageClassName: cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
