apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gobland-it-code-python
spec:
  storageClassName: cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
