apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: glit
  name: gobland-it-mariadb
  labels:
    tier: glit
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
        tier: glit
    spec:
      containers:

      - image: mariadb/server:10.3
        name: gobland-it-mariadb
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gobland-it-mariadb-secret
              key: pass
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: gobland-it-mariadb-db
          mountPath: /var/lib/mysql

      volumes:
      - name: gobland-it-mariadb-db
        persistentVolumeClaim:
          claimName: gobland-it-mariadb-db
