apiVersion: v1
kind: Service

metadata:
  namespace: glit
  name: gobland-it-mariadb-svc
  labels:
    tier: glit
spec:
  selector:
    app: mariadb
    tier: glit
  ports:
  - protocol: TCP
    port: 3306
