apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: glit
  name: gobland-it-backup
  labels:
    tier: glit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup
      tier: glit
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backup
        tier: glit
    spec:
      restartPolicy: Always

      containers:
      - name: gobland-it-backup
        image: lordslair/easydbbackup:1.2.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: 32Mi
            cpu: 100m
          requests:
            memory: 16Mi
            cpu: 10m
        env:
          - name: DB_LIST
            valueFrom:
              secretKeyRef:
                name: gobland-it-backup-secret
                key: dblist
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: gobland-it-mariadb-secret
                key: host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: gobland-it-mariadb-secret
                key: port
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: gobland-it-mariadb-secret
                key: pass
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: gobland-it-mariadb-secret
                key: user
          - name: RCLONE_CONFIG_PCS_TYPE
            valueFrom:
              secretKeyRef:
                name: gobland-it-backup-secret
                key: pcstype
          - name: RCLONE_CONFIG_PCS_ENV_AUTH
            valueFrom:
              secretKeyRef:
                name: gobland-it-backup-secret
                key: pcsenvauth
          - name: RCLONE_CONFIG_PCS_AUTH_VERSION
            valueFrom:
              secretKeyRef:
                name: gobland-it-backup-secret
                key: pcsauthversion
          - name: RCLONE_CONFIG_PCS_TENANT_DOMAIN
            valueFrom:
              secretKeyRef:
                name: gobland-it-backup-secret
                key: pcstenantdomain
          - name: RCLONE_CONFIG_PCS_DOMAIN
            valueFrom:
              secretKeyRef:
                name: gobland-it-backup-secret
                key: pcsdomain
          - name: RCLONE_CONFIG_PCS_AUTH
            valueFrom:
              secretKeyRef:
                name: gobland-it-backup-secret
                key: pcsauth
          - name: RCLONE_CONFIG_PCS_TENANT
            valueFrom:
              secretKeyRef:
                name: gobland-it-backup-secret
                key: pcstenant
          - name: RCLONE_CONFIG_PCS_USER
            valueFrom:
              secretKeyRef:
                name: gobland-it-backup-secret
                key: pcsuser
          - name: RCLONE_CONFIG_PCS_KEY
            valueFrom:
              secretKeyRef:
                name: gobland-it-backup-secret
                key: pcskey
          - name: RCLONE_CONFIG_PCS_REGION
            valueFrom:
              secretKeyRef:
                name: gobland-it-backup-secret
                key: pcsregion
          - name: RCLONE_CONFIG_PCS_DIR
            valueFrom:
              secretKeyRef:
                name: gobland-it-backup-secret
                key: pcsdir
