apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: glit
  name: gobland-it-perl
  labels:
    tier: glit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perl
      tier: glit
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: perl
        tier: glit
    spec:
      restartPolicy: Always

      containers:
      - name: gobland-it-perl
        image: alpine:3.7
        command: ["/bin/sh"]
        args: [
         "-c",
         "(
              wget -O - https://raw.githubusercontent.com/lordslair/gobland-bot/master/kubernetes/perl/entrypoint.sh | sh
          ) || echo 1"
        ]
        env:
        - name: DBLIST
          valueFrom:
            secretKeyRef:
              name: gobland-it-perl-secret
              key: dblist
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gobland-it-mariadb-secret
              key: pass
        - name: MARIADB_HOST
          valueFrom:
            secretKeyRef:
              name: gobland-it-mariadb-secret
              key: host
